name: Release

on: { push: { tags: '*' } }

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # for creating a GitHub release
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        # fetch full history for correct commits parsing by relion
        with: { fetch-depth: 0 }

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with: { version: 10.17.1 }

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with: { node-version: 24.9.0, cache: pnpm }

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build:prod

      - name: Lint
        run: pnpm lint

      - name: Create release archive
        run: |
          ARCHIVE_NAME=${GITHUB_REPOSITORY##*/}-$TAG.zip
          echo ARCHIVE_NAME=$ARCHIVE_NAME >> $GITHUB_ENV
          zip -r $ARCHIVE_NAME manifest.json main.js styles.css

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $TAG \
            --title $TAG \
            --notes "$(pnpm --silent release:github)" \
            --draft \
            main.js manifest.json styles.css $ARCHIVE_NAME